# Triggers
trigger:
  branches:
    include:
      - 'main'
      - 'release-*'
  tags:
    include:
      - '*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

# Stages
stages:
  - stage: build
    displayName: build
    jobs:
      - job: 'Main branch build try'
        displayName: 'Build'
        # Set timeout for jobs
        timeoutInMinutes: 60
        # Base system
        pool:
          vmImage: 'Ubuntu-18.04'
        # Pipeline steps
        steps:
          - bash: make prepare
            displayName: "Download kafka"
          - bash: make docker_build
            displayName: "Build new image"